version: '3.8'

services:
  # Production builder – runs your React/Electron build
  builder:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV:-production}
        GEMINI_API_KEY: ${GEMINI_API_KEY}
    container_name: free-cluely-builder
    environment:
      - NODE_ENV=production
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    command: npm run build
    volumes:
      - ./release:/app/release
    networks:
      - free-cluely-network

  # Production Electron app – packages the built assets into your desktop bundle
  electron-app:
    build:
      context: .
      dockerfile: Dockerfile.electron
      args:
        NODE_ENV: ${NODE_ENV:-production}
        GEMINI_API_KEY: ${GEMINI_API_KEY}
    container_name: free-cluely-electron-prod
    environment:
      - NODE_ENV=production
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DISPLAY=:99
    command: >
      bash -c "Xvfb :99 -screen 0 1024x768x16 -ac &&
               sleep 5 &&
               npm run app:build"
    volumes:
      - ./release:/app/release
    depends_on:
      - builder
    networks:
      - free-cluely-network

networks:
  free-cluely-network:
    driver: bridge
